pipeline{
    agent any
    stages{
        stage('Git clone') {
            steps {
                 // Get some code from a GitHub repository
                git 'https://github.com/dnyaneshvarsultane/Hello-world.git'
            }
        }
        stage('Maven Build') {
            steps{
            sh 'mvn clean package -DskipTest=true'
          }
        }
        stage('Build Docker') {
            steps{
                script {
                    dockerImage = docker.build(registry)
                }
            }
        }
        stage('remove unused docker image') {
            steps{
                //sh"docker rmi ${env.BUILD_NUMBER}"
                sh "docker rmi:latest"
            }
        }
    }
    post{
        failure {
            echo "Build is failed"
        }
        success {
            echo "Build is successful"
        }
    }
}
