pipeline {
    environment {
    DOCKER_HOST = 'tcp://43.205.228.100/:2375'
}
    agent any
    stages {
        stage('Git clone') {
            steps {
                git 'https://github.com/dnyaneshvarsultane/Hello-world.git'
            }
        }
        stage('Maven Build') {
            steps {
                sh 'mvn clean package -DskipTest=true'
            }
        }
        stage('Build Docker') {
            steps {
                script {
                def dockerImage = docker.build("Docker")
                }
            }
        }
        stage('Remove Unused Docker Image') {
            steps {
                sh "docker rmi my-image:${env.BUILD_NUMBER}"
            }
        }
    }
    post {
        always {
            cleanWs()
        }
        success {
            echo "Build is successful"
        }
        failure {
            echo "Build failed"
        }
    }
}
