pipeline {
    agent any
    environment {
        DOCKER_HOST = 'tcp://15.206.167.109'
    }
    stages {
        stage('Git clone') {
            steps {
                 git 'https://github.com/dnyaneshvarsultane/Hello-world.git'
            }
        }
        stage('Maven Build') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }
        stage('Build Docker') {
            steps {
                script {
                  def dockerImage = docker.build("docker_jar:latest")
                }
            }
        }
        stage('Remove Unused Docker Image') {
            steps {
                sh "docker rmi my-image:${env.BUILD_NUMBER}"
            }
        }
    }
    post {
        always {
            cleanWs()
        }
        success {
            echo "Build is successful"
        }
        failure {
            echo "Build failed"
        }
    }
}
