pipeline {
    environment {
    DOCKER_HOST = 'tcp:65.1.114.8/:2375'
}
    agent any
    stages {
        stage('Git clone') {
            steps {
                git 'https://github.com/dnyaneshvarsultane/springboot-hello.git'
            }
        }
        stage('Maven Build') {
            steps {
                sh 'mvn clean package -DskipTest=true'
            }
        }
        stage('Build Docker') {
            steps {
                script {
              def dockerImage = docker.build("Docker").withBuildArg("DOCKER_HOST", "tcp://65.1.114.8/:2375").withRun("-v /var/run/docker.sock:/var/run/docker.sock").tag("my-image:${env.BUILD_NUMBER}")
                }
            }
        }
        stage('Remove Unused Docker Image') {
            steps {
                sh "docker rmi my-image:${env.BUILD_NUMBER}"
            }
        }
    }
    post {
        always {
            cleanWs()
        }
        success {
            echo "Build is successful"
        }
        failure {
            echo "Build failed"
        }
    }
}
