pipeline {
    agent any
    environment {
        DOCKER_HOST = 'tcp://65.1.114.8:2375'
    }
    stages {
        stage('Git clone') {
            steps {
                git 'https://github.com/dnyaneshvarsultane/springboot-hello.git'
            }
        }
        stage('Maven Build') {
            steps {
                sh 'mvn clean package -DskipTests=true'
            }
        }
        stage('Build Docker') {
            steps {
                script {
                    docker.build("my-image:${env.BUILD_NUMBER}")
                        .withBuildArg("DOCKER_HOST", "${DOCKER_HOST}")
                        .withRun("-v /var/run/docker.sock:/var/run/docker.sock")
                        .push()
                }
            }
        }
        stage('Remove Unused Docker Image') {
            steps {
                sh "docker rmi my-image:${env.BUILD_NUMBER}"
            }
        }
    }
    post {
        always {
            cleanWs()
        }
        success {
            echo "Build is successful"
        }
        failure {
            echo "Build failed"
        }
    }
}
