pipeline {
    agent any 
    stages {
        stage('git checkout') {
            steps {
                git credentialsId: 'github-credential', url: 'https://github.com/dnyaneshvarsultane/springboot-maven-micro.git'
            }
        }
        stage('build the package') {
            steps {
                sh 'mvn clean package'
            }
        }
        stage('sonar quality check') {
            steps {
                script {
                    withSonarQubeEnv(installationName: 'sonarqube-10') {
                        withCredentials([string(credentialsId: 'devops-jenkins', variable: 'sonar_login')]) {
                            sh 'mvn sonar:sonar -Dsonar.login=$sonar_login'
                        }
                    }
                }
            }
        }
        stage('Quality Gate') {
            steps {
                timeout(time: 1, unit: 'HOURS') {
                    def qg = waitForQualityGate()
                    if (qg.status != 'OK') {
                        error "Pipeline aborted due to quality gate failure: ${qg.status}"
                    }
                }
            }
        }
    }
}
}
