pipeline{
  agent any 
  environment{
    registry = '078187675174.dkr.ecr.ap-south-1.amazonaws.com/devops'
  }
  stages{
    stage('git checkout'){
      steps{
        git credentialsId: 'github-credential', url: 'https://github.com/dnyaneshvarsultane/springboot-maven-micro.git'
      }
    }
    stage('build the package'){
      steps{
        sh 'mvn clean package'
      }
    }
    stage('Building our image') {
       steps{
       script {
       dockerImage = docker.build registry + ":$BUILD_NUMBER"
     }
   }
   }
 }
}
